version: '3.8'

volumes:
  database_cs:
  static_cs:
  media_cs:

services:

  db_cs:
    image: postgres:15-alpine
    volumes:
      - database_cs:/var/lib/postgresql/data/
    env_file:
      - backend/cleanpro/.env

  redis:
    image: redis:7.2.1-alpine

  backend:
    build:
      context: backend/cleanpro
      dockerfile: Dockerfile
    env_file: backend/cleanpro/.env
    volumes:
      - static_cs:/app/static
      - media_cs:/app/media
    depends_on:
      - db_cs
      - redis

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - static_cs:/app/dist
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./redocs/:/usr/share/nginx/html/redocs/
      - static_cs:/var/html/static/
      - media_cs:/var/html/media/
    depends_on:
      - backend
      - frontend
