##########################################################################
################################# TOKENS #################################
##########################################################################

@admin_token = 0ec9a2e114394958a354bf038609bbc3593ff166

@login = http://127.0.0.1:80/api/auth/token/login/
@logout = http://127.0.0.1:80/api/auth/token/logout/

@orders = http://127.0.0.1:80/api/orders/

@ratings = http://127.0.0.1:80/api/ratings/

@users = http://127.0.0.1:80/api/users/
@users_me = http://127.0.0.1:80/api/users/me/

###
POST {{login}} HTTP/1.1
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "admin"
}

###
POST {{logout}} HTTP/1.1
Authorization: Token 0ec9a2e114394958a354bf038609bbc3593ff166

### 
GET {{users}} HTTP/1.1
Authorization: Token 0ec9a2e114394958a354bf038609bbc3593ff166

###
PUT {{users}}1/ HTTP/1.1
Authorization: Token 0ec9a2e114394958a354bf038609bbc3593ff166
Content-Type: application/json

{
    "username": "Супер администратор",
    "email": "admin@email.com",
    "phone": "+79991112233",
    "address": {
        "city": "Москва",
        "street": "Питерская",
        "house": 14,
        "entrance": 1,
        "floor": 150,
        "apartment": 999
    }
}

### 
GET {{users_me}} HTTP/1.1
Authorization: Token 0ec9a2e114394958a354bf038609bbc3593ff166

### 
POST {{users}}confirm_email/ HTTP/1.1
Content-Type: application/json

{
  "email": "myemail@email.com"
}

###
GET {{ratings}} HTTP/1.1

###
GET {{ratings}}?limit=30 HTTP/1.1

###
POST {{ratings}} HTTP/1.1
Authorization: Token 0ec9a2e114394958a354bf038609bbc3593ff166

###
GET {{orders}} HTTP/1.1

###
POST {{orders}} HTTP/1.1
Content-Type: application/json

{
    "user": {
        "username": "Вика",
        "email": "elpastel@email.com",
        "phone": "+7 777 777 77 77"
    },
    "comment": "Que paso, amigo? ;)",
    "total_sum": 1000000,
    "cleaning_type": "1",
    "services": [
        {
            "id": 1,
            "amount": 2
        },
        {
            "id": 3,
            "amount": 1
        }
    ],
    "address": {
        "city": 11,
        "street": 11,
        "house": 15,
        "entrance": 15,
        "floor": 15,
        "apartment": 15
    },
    "cleaning_date": "2023-11-12",
    "cleaning_time": "01:30"
}
