# Generated by Django 4.2.4 on 2023-08-23 18:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apartment",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Квартира"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="user",
            name="house",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, verbose_name="Дом"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region="RU",
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, verbose_name="Улица"),
        ),
    ]
