# Generated by Django 4.2.4 on 2023-09-10 10:01

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='apartment',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='entrance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
