# Generated by Django 4.2.4 on 2023-08-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_apartment_user_city_user_house_user_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
