# Generated by Django 4.2.4 on 2023-08-23 18:54

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
