# Generated by Django 4.2.4 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="house",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Дом"
            ),
        ),
    ]
