# Generated by Django 4.2.4 on 2023-08-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_name_alter_user_city_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
