# Generated by Django 4.2.4 on 2023-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_roles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Roles",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admin", "Администатор")],
                default="user",
                max_length=5,
                verbose_name="Роль",
            ),
        ),
    ]
