# Generated by Django 4.2.4 on 2023-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_delete_roles_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Адрес электронной почты"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
