# Generated by Django 4.2.4 on 2023-08-26 11:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_name_user_first_name_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="RU", verbose_name="Номер телефона"
            ),
        ),
    ]
