# Generated by Django 4.2.4 on 2023-08-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('users', '0016_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='service.adress', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
    ]
