# Generated by Django 4.2.4 on 2023-09-08 14:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order_status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=256, verbose_name='Статус')),
                ('pay_status', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('creation_time', models.TimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cleaning_date', models.DateField(db_index=True, verbose_name='Дата уборки')),
                ('cleaning_time', models.TimeField(verbose_name='Время уборки')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.adress', verbose_name='Услуги')),
            ],
            options={
                'ordering': ['-cleaning_date'],
            },
        ),
        migrations.CreateModel(
            name='Service_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('maintenance', 'Поддерживающая уборка'), ('general', 'Генеральная уборка'), ('repair', 'Уборка после ремонта'), ('holiday', 'Уборка после мероприятия'), ('windows', 'Мытье окон')], default='maintenance', max_length=256, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Сумма')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.order', verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.service_package', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
